### PR TITLE
#41 - BrowserSync Integration

### PR DESCRIPTION
**Pull request by bartekus**
Intended Scope of Work:
BrowserSync Integration - [Status Successful]

As per @eyko suggestion [referenced below], a successful attempt have been made at integrating BrowserSync

> Originally posted by @eyko on Jan 26, 2016, 11:22 AM MST

```
Hi @Bartekus, good point.

To use browser-sync, all you need need is to proxy it to the express server. These two lines are enough to use browserSync:

const browserSync = require('browser-sync');
browserSync.init({
  proxy: `${config.server.hostname}:${port}`
});
Since the express server is already serving on port 3000 (which is also the browserSync default port), browserSync would start in port 3001 and 3002. My suggestion would be to change the port 4000 for example, and then proxy from browsersync (that way browsersync gets port 3000).

app.listen(4000, config.server.hostname);
browserSync.init({
  proxy: `${config.server.hostname}:4000`
});
```

### CODE REVIEW

**Comment by vincemtnz** [comment]
The branch needs updating so that we can merge this.

It'd be best if we could hide this behind a `--with-browsersync` command line flag so we don't _always_ have to use use browser sync. We can also add a new npm script for it (e.g. `npm run dev:bs`)

**Comment by bartekus** [comment]
I'm on it, just few more min as I gotta test thru the solution.

**Comment by vincemtnz** [comment]
@Bartekus thanks! :rocket:

**Comment by bartekus** [comment]
@eyko, my pleasure! :D :+1:

**Pull request merged**
