### PR TITLE
Add estraverse-fb and remove failing react/prefer-stateless-function rule

### PR DESCRIPTION
**Pull request by ro-savage**
For this boilerplate to work out of the box estraverse-fb needs to be added to the package.json.

And either the eslint rule 'react/prefer-stateless-function' need to be overwritten and turned off. Or the components re-written to be stateless.

I choose the quicker option :)

### CODE REVIEW

**Comment by mcalthrop** [comment]
Thanks for trying out the code in the repo @ro-savage!

I'm puzzled by the issues you've seen – the Travis build works fine, and it works locally as well.

A couple of questions:
- What OS are you using?
- And what versions of node and npm?
- why do you think estraverse-fb is missing? (haven't had any warnings or errors either locally, or on Travis AFAIK)

Our local setup is OSX 10.11.3, node 5.3.0 (the Travis build specifies 5.4.0) and npm 3.3.12. It might be the case that we need to add a **Prerequisites** section to the **README**.

Matt

**Comment by ro-savage** [comment]
Hi,

Did a little bit more research. 

The _estraverse-fb_ missing issue is related to _babel-eslint_ requiring a package that no longer exists in _eslint_. The way to resolve is either to install _estraverse-fb_ package directly, or lockdown _eslint to 2.2.0_ (or add the package to babel-eslint?)
See: https://github.com/eslint/eslint/issues/5476

Can cancel this pull request, and fix it up as your see fit. I have locked down eslint to 2.2.0 for my other projects for now.

Just in case, for the other questions
OSX 1.0.11.3
NPM 3.6.0
Node 5.7.0

**Comment by mcalthrop** [comment]
@ro-savage: thanks for digging, and finding the cause. I removed my `node_modules` directory, re-ran `npm install`, and am now seeing the error you described (the version of `eslint` installed is `2.3.0`).

I tend to agree with you and @jhabdas: the better option is [to not upgrade until the problem is solved](https://github.com/eslint/eslint/issues/5476#issuecomment-192891771).

Thanks for the offer to make changes; I think it will be quicker for me to make the change to `package.json` to lock `eslint` at version `2.2.0` instead of `^2.2.0`.

**Comment by mcalthrop** [comment]
What I've also done is to lock `eslint-config-airbnb` to version `6.0.2`, which fixes the eslint errors. We may go to more recent versions in the future.

The merged PR is #82.

Thanks for your help!

**Comment by ro-savage** [comment]
Awesome. Thanks.

This boilerplate you put together is really useful for getting a better understand of how to put together a more real world application than other tutorials/boilerplates out there. Keep up the good work!

**Comment by mcalthrop** [comment]
Great to hear. I've learned a lot myself!

**Pull request closed without merging**
