### PR TITLE
Modules Update - Major Versions [P]

### PR DESCRIPTION
**Pull request by bartekus**
Intended Scope of Work:
Upgrade modules with major update versions.

Development dependencies:
- eslint-config-airbnb 3.1.0 -> 4.0.0 [PROBLEM]
- html-webpack-plugin 1.7.0 -> 2.7.2
- phantomjs 1.9.19 -> 2.1.3
  
  [WHY] : [Require braces in arrow function body (arrow-body-style)](http://eslint.org/docs/rules/arrow-body-style.html)
  
  [SOLUTION] :
- A. Modify to conditional-pass (shows as warning) by adding:  "arrow-body-style":[1, "as-needed"](Currently employed)
- B. Disable the check  altogether by adding: "arrow-body-style":[0, "as-needed"](I do not posses enough experience to recommended or not recommend this)
- C.(In-Progress) Both my colleague and I have added our voice in favour of allowing such patterns as it's becoming increasingly more common with with HOC's and middlewares
  
  Here is the issue being discussed:
  [arrow-body-style: [2, "as-needed"] should ignore function bodies that return another block/function #4353](https://github.com/eslint/eslint/issues/4353)
  
  Problem Log:
  Absence of "arrow-body-style":[0, "as-needed"] or presence of "arrow-body-style":[2, "as-needed"]  causes:
  
  ```
  /Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/api/user.js
    6:48  error  Unexpected block statement surrounding arrow body  arrow-body-style
  10:61  error  Unexpected block statement surrounding arrow body  arrow-body-style
  
  /Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/components/DropdownProfileCard/DropdownProfileCard.js
   5:62  error  Unexpected block statement surrounding arrow body  arrow-body-style
  
  /Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/components/Login/Login.js
   3:26  error  Unexpected block statement surrounding arrow body  arrow-body-style
  
  /Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/containers/AdminPageLayout.js
   8:36  error  Unexpected block statement surrounding arrow body  arrow-body-style
  
  /Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/containers/HeroPageLayout.js
   8:35  error  Unexpected block statement surrounding arrow body  arrow-body-style
  
  /Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/containers/LanguageSelectionDropdown/LanguageSelectionDropdown.js
   34:44  error  Unexpected block statement surrounding arrow body  arrow-body-style
  
  /Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/pages/LandingPage/LandingPage.js
   76:36  error  Unexpected block statement surrounding arrow body  arrow-body-style
  
  /Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/pages/LandingPage/LandingPageHero.js
   7:36  error  Unexpected block statement surrounding arrow body  arrow-body-style
  
  /Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/redux/modules/auth/auth-actions.js
    80:45  error  Unexpected block statement surrounding arrow body  arrow-body-style
  106:46  error  Unexpected block statement surrounding arrow body  arrow-body-style
  
  /Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/redux/modules/user/user-actions.js
   61:62  error  Unexpected block statement surrounding arrow body  arrow-body-style
  68:52  error  Unexpected block statement surrounding arrow body  arrow-body-style
  75:53  error  Unexpected block statement surrounding arrow body  arrow-body-style
  
  ✖ 14 problems (14 errors, 0 warnings)
  ```
  
  Presence of "arrow-body-style":[1, "as-needed"] allow for conditional pass with warrning:

```
/Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/api/user.js
   6:48  warning  Unexpected block statement surrounding arrow body  arrow-body-style
  10:61  warning  Unexpected block statement surrounding arrow body  arrow-body-style

/Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/components/DropdownProfileCard/DropdownProfileCard.js
  5:62  warning  Unexpected block statement surrounding arrow body  arrow-body-style

/Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/components/Login/Login.js
  3:26  warning  Unexpected block statement surrounding arrow body  arrow-body-style

/Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/containers/AdminPageLayout.js
  8:36  warning  Unexpected block statement surrounding arrow body  arrow-body-style

/Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/containers/HeroPageLayout.js
  8:35  warning  Unexpected block statement surrounding arrow body  arrow-body-style

/Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/containers/LanguageSelectionDropdown/LanguageSelectionDropdown.js
  34:44  warning  Unexpected block statement surrounding arrow body  arrow-body-style

/Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/pages/LandingPage/LandingPage.js
  76:36  warning  Unexpected block statement surrounding arrow body  arrow-body-style

/Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/pages/LandingPage/LandingPageHero.js
  7:36  warning  Unexpected block statement surrounding arrow body  arrow-body-style

/Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/redux/modules/auth/auth-actions.js
   80:45  warning  Unexpected block statement surrounding arrow body  arrow-body-style
  106:46  warning  Unexpected block statement surrounding arrow body  arrow-body-style

/Users/Bart/Dev/BIN/WORK/opencredo-react-boilerplate/src/redux/modules/user/user-actions.js
  61:62  warning  Unexpected block statement surrounding arrow body  arrow-body-style
  68:52  warning  Unexpected block statement surrounding arrow body  arrow-body-style
  75:53  warning  Unexpected block statement surrounding arrow body  arrow-body-style

✖ 14 problems (0 errors, 14 warnings)
```

### CODE REVIEW

**Comment by mcalthrop** [comment]
Hi @Bartekus 

Thanks for looking into this, and sorry for the delay... very busy day yesterday.

These changes look great, so all good to go after you've done the following:
- rebase your branch from `master`, as we have made a few commits since you raised this PR
- please also modify the relevant parts of the code so that we no longer have any warnings.
  For example, in `api/user.js`, you'll need to change this:

``` js
export const getProfile = (): Promise<User> => {
  return axios.get('/api/profile.json').then(response => response.data);
};
```

to this:

``` js
export const getProfile = (): Promise<User> =>
  axios.get('/api/profile.json').then(response => response.data);
```

Hope that's all clear – let me know if you have any questions.

cheers

Matt
cc @eyko

**Comment by bartekus** [comment]
It's all good Matt, I'm on it and in few minutes I'll be sending the corrected and updated pull

**Comment by bartekus** [comment]
after fixing everything should I remove this "arrow-body-style":[1, "as-needed"], leave it the way it is right now, triggering warning, or make it more stricter with using of 2 and always?

**Comment by vincemtnz** [comment]
Let's remove `"arrow-body-style":[1, "as-needed"]` then so that builds can fail if we miss these (that way we can catch them before any merges).

**Comment by mcalthrop** [comment]
:+1:

**Pull request closed without merging**
