### PR TITLE
Add app-config; fixes #17

### LINKED ISSUE #17: I see something tasty brewing here!
How could I be of an assistance gentlemen?

### PR DESCRIPTION
**Pull request by mcalthrop**

### CODE REVIEW

**Comment by vincemtnz** [comment]
This would be very environment specific (e.g. api urls, client tokens, etc) so having it in version control could turn out to be counterproductive. We should probably add a note in the documentation about it if we're including it.

**Comment by mcalthrop** [comment]
Good call. Private or env-specific values could be abstracted by specifying them as environment variables.

**Comment by vincemtnz** [comment]
You mean like the `__DEBUG__` or `DEVELOPMENT` / `PRODUCTION` globals?

**Comment by mcalthrop** [comment]
Possibly; but also API keys/tokens. These can be defined in the Travis job, for example – no need to commit to codebase.

**Pull request merged**
